### ISSUE TITLE
monontic Typo

### ISSUE THREAD

**Issue by f35f0ef9d0e827dae86552d3899f78fc** [oleerik/steamscript#16]
Seems like there is a typo somewhere that should be corrected to "monotonic".
My version of monotonic was installed as a dependency to `pip install python-valve`.
```
$ pip list | grep mono
monotonic (1.4)
$ ./rusts.py 
name 'monontic' is not defined
```

**Comment by lillelilje** [comment]
This is in python-valve, not this script. Get python-valve through git and it works :)
